import './main.css'

export const metadata = {
  title: "abolfazl jamshidi",
  description: "generated by abolfazl_j10",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        {children}
      </body>
    </html>
  );
}
